name: PlotRate
version: 1.1.3
api: 5.0.0
main: supercrafter333\PlotRate\PlotRate
author: supercrafter333, ZhaDev
load: POSTWORLD
depend: MyPlot
commands: 
 pr:
  description: plotrate command
  permission: plot.cmd
  
permissions:
 plot.cmd:
  default: true
  
